package com.ca.control.enums;

public enum APIsEnum {

	FINALIZAR_REGISTRO_HORA, INICIO_DIA, LISTA_REGISTROS_HORA_USUARIO_X_DIA, PAUSA_REINICIO, ACTUALIZAR_REGISTRO_HORA,
	REGISTRO_SIN_FINALIZAR, LISTAR_LUGAR_TRABAJO, LISTAR_TIPO_HORAS, HORAS_TABAJADAS, ESTADO_DIA, REGISTRO_BORRADO,
	REGISTRO_ACTUALIZADO
}
